// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3xKW1dbvQ22yJgp71MmgTxrMDDd40EwQ',
    appId: '1:450497142059:web:50c6bddeecb2236a5db96e',
    messagingSenderId: '450497142059',
    projectId: 'management-seeking-apartment',
    authDomain: 'management-seeking-apartment.firebaseapp.com',
    storageBucket: 'management-seeking-apartment.firebasestorage.app',
    measurementId: 'G-3TP4MVN1TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrXiN_6KcHioWjSvFxYgnuSnN9x3eDuGc',
    appId: '1:450497142059:android:5b6a65445f95f7f65db96e',
    messagingSenderId: '450497142059',
    projectId: 'management-seeking-apartment',
    storageBucket: 'management-seeking-apartment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHz-N8WJwXS2aFH85fuQ_og-2xmdjTQBo',
    appId: '1:450497142059:ios:444be436f89b32a95db96e',
    messagingSenderId: '450497142059',
    projectId: 'management-seeking-apartment',
    storageBucket: 'management-seeking-apartment.firebasestorage.app',
    iosBundleId: 'com.example.quanLyTimKiemPhongTroFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHz-N8WJwXS2aFH85fuQ_og-2xmdjTQBo',
    appId: '1:450497142059:ios:444be436f89b32a95db96e',
    messagingSenderId: '450497142059',
    projectId: 'management-seeking-apartment',
    storageBucket: 'management-seeking-apartment.firebasestorage.app',
    iosBundleId: 'com.example.quanLyTimKiemPhongTroFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3xKW1dbvQ22yJgp71MmgTxrMDDd40EwQ',
    appId: '1:450497142059:web:6ec24c214def7dcb5db96e',
    messagingSenderId: '450497142059',
    projectId: 'management-seeking-apartment',
    authDomain: 'management-seeking-apartment.firebaseapp.com',
    storageBucket: 'management-seeking-apartment.firebasestorage.app',
    measurementId: 'G-XD0ET1P5NG',
  );

}