authentication:
    Identifier: String
    Providers: String
    Created: Datetime
    Signed In: Datetime
    User UID: String

user:
    Document ID	: Sting
    Balance	: Int64
    CCCD	: String
    Email	: String
    FullName	: String
    Password	: String
    Phone	: String
    Role   : String
    Status : String
amenity:
    Document ID	: String
    Description	: String
    Name : String
amenityInApartment:
    Document ID	: String
    AmenityID	: String
    ApartmentID	: String
    IsAvailable : Boolean
apartment:
    Document ID	: String
    Address	: String
    CheckInTime	: String
    CheckOutTime	: String
    CodeApartment	: String
    DailyRate	: Int64
    Description	: String
    Latitude	: Double
    Longitude	: Double
    MaxOccupancy	: Int64
    Password : String
    pathImage: Array<String>
    Requirements: Array<String>
    Status: String
    Type: String
    UserId: String

contract:
    Document ID	: String
    ApartmentId	: String
    CreatedDate	:Timestamp
    EndDate	: String
    EscrowAmount	
    StartDate	: String
    Status	: String
    UserID : String
invoice:
    Document ID	: String
    ApartmentId	: String	
    Code	    : Null
    ContractId	: String
    IssueDate	:Timestamp
    Note	    :Null
    Status	    : String
    TotalAmount : Int64
invoiceDetail:
    Document ID	: String
    Description	: String
    Quantity	: Int64
    Subtotal	: Int64
    UnitPrice   : Int64
iot_device_in_apartment:
    Document ID	: String
    ApartmentID	: String
    CreationDate:Timestamp
    DeviceID	: String
    IoTDeviceID	: String
    Otp	        : String
    PingCode	: String
    RoomCode	: String
    Status      : String
iot_devices:
    Document ID	: String
    Description	: String
    Name        : String
message:
    Document ID	: String
    Content	    : String
    ReceiverID	: String
    SenderID	: String
    SentDate	:Timestamp
    Status      : String
posts:
    Document ID	: String
    ApartmentID	: String
    CreationDate: Timestamp
    Description	: String
    Header	    : String
    Status      : String
transaction:
    Document ID	: String
    Amount	    : Int64
    GatewayTransactionId : String
    InvoiceID	: String
    PaymentDate	: Timestamp
    PaymentMethod : String
    Status	    : String
    Type	    : String
    UserID      : String
walletBlockchains:
    Document ID	: String
    CredentialsCertificate	: String
    CredentialsPrivateKey	: String
    MSPID	                : String
    Type	                : String
    UserID                  : String