' alt + d
@startuml usecase_admin-diagram
' skinparam shadowing false
' skinparam backgroundColor #f9f9f9
' skinparam usecase {
'     BackgroundColor #e6f7ff
'     BorderColor #1890ff
'     FontColor #000000
'     FontSize 14
'     Shadowing true
' }
' skinparam actor {
'     BackgroundColor #fff2e8
'     BorderColor #fa8c16
'     FontColor #000000
'     FontSize 14
' }
' skinparam rectangle {
'     BackgroundColor #fffbe6
'     BorderColor #d48806
'     FontColor #000000
'     FontSize 18
'     Shadowing true
' }
' skinparam note{
'     BackgroundColor #faf2b9
'     BorderColor #c51c1c
' }
left to right direction

actor "Quản trị viên" as Admin

rectangle "  "{
usecase "Đăng nhập" as login
usecase "Quản lý tài khoản người dùng" as manage_user_accounts
note top of manage_user_accounts: Duyệt xác minh chủ căn hộ, Tìm kiếm, Xem, Khóa, Mở khóa

usecase "Quản lý tài khoản" as manage_account
note bottom of manage_account: Xem, Thay đổi thông tin, Đổi mật khẩu, Đăng xuất

usecase "Tìm kiếm bài đăng" as search_posts
usecase "Xem chi tiết bài đăng" as view_post_details
search_posts . view_post_details: extend
usecase "Xóa bài đăng" as delete_post
usecase "Duyệt bài đăng" as approve_posts

usecase "Quản lý thiết bị IoT" as manage_iot_devices
note bottom of manage_iot_devices: Tìm kiếm, Thêm, Sửa, Xóa, Xem và kiểm tra trạng thái kết nối

usecase "Xem danh sách thiết bị đã kết nối" as view_list_device_connected

usecase "Tìm kiếm yêu cầu đặt phòng" as search_booking
usecase "Xem yêu cầu đặt phòng" as view_booking_requests
search_booking . view_booking_requests: extend

usecase "Quản lý giao dịch" as manage_transactions
note bottom of manage_transactions: Xem, duyệt yêu cầu rút tiền, từ chối yêu cầu rút tiền

usecase "Thống kê" as statistics



(login) -- (Admin)
(manage_user_accounts) -- (Admin)
(manage_account) -- (Admin)
(search_posts) -- (Admin)
(approve_posts) -- (Admin)
(delete_post) -- (Admin)
(manage_iot_devices) -- (Admin)
(view_list_device_connected) -- (Admin)
(search_booking) -- (Admin)
(manage_transactions) -- (Admin)
(statistics) -- (Admin)
}
@enduml
