@startuml taocanho-sequence-diagram
title "Sơ đồ trình tự \ntạo căn hộ"
actor User as User
boundary ":Mobile \nApp" as MobileApp
control ":Mobile \nControl" as MobileControl
control ":Web \nControl" as WebControl
control ":Smart \nContract" as SmartContract
entity ":Offchain \nDatabase" as OffchainDatabase
entity ":Onchain \nDatabase" as OnchainDatabase

User -> MobileApp: lấy dữ liệu \nbiểu mẫu \nthêm căn hộ
activate User
activate MobileApp
MobileApp -> MobileControl: yêu cầu dữ liệu \nhiển thị biểu mẫu \nthêm căn hộ
activate MobileControl
MobileControl -->MobileApp: hiển thị biểu mẫu \nthêm căn hộ

User -> MobileApp: nhập thông tin \ncăn hộ mới \nvà gửi yêu cầu
MobileApp -> MobileControl: yêu cầu thêm \ncăn hộ mới
MobileControl -> WebControl: gửi yêu cầu \nthêm căn hộ mới
activate WebControl
WebControl -> OffchainDatabase: xác thực và \ngửi yêu cầu \nlưu thông tin \ncăn hộ mới
activate OffchainDatabase
'trường hợp thành công
    ' trường hợp offchain
        'thành công
        alt Thêm dữ liệu offchain \nthất bại
            OffchainDatabase --> WebControl: lỗi \nthêm căn hộ mới
            deactivate OffchainDatabase
            WebControl --> MobileControl: thông báo lỗi \nthêm căn hộ mới
            deactivate WebControl
            MobileControl --> MobileApp: thông báo \nlỗi thêm căn hộ mới
            deactivate MobileControl
        else Thêm dữ liệu \noffchain thành công
            OffchainDatabase --> WebControl: thêm căn hộ mới \nthành công
            deactivate OffchainDatabase
            'trường hợp onchain
            activate WebControl
            WebControl -> SmartContract: tạo giao dịch \nthêm căn hộ mới
            activate SmartContract
                'thất bại
            alt Xác nhận giao dịch \nthất bại
                SmartContract --> WebControl: lỗi giao dịch \nthêm căn hộ mới
                deactivate SmartContract
                activate MobileControl
                WebControl --> MobileControl: thông báo lỗi \ngiao dịch \nthêm căn hộ mới
                deactivate WebControl
                MobileControl --> MobileApp: thông báo lỗi \nthêm căn hộ mới
                deactivate MobileControl
            else Xác nhận giao dịch \nthành công
                'thành công
                SmartContract --> WebControl: xác nhận giao dịch \nthêm căn hộ mới \nthành công
                deactivate SmartContract
                activate WebControl
                WebControl -> OnchainDatabase: lưu thông tin \ngiao dịch \nthêm căn hộ mới
                activate OnchainDatabase
                OnchainDatabase --> WebControl: thêm giao dịch \nthêm căn hộ mới \nthành công
                deactivate OnchainDatabase
                activate MobileControl
                WebControl --> MobileControl: thêm căn hộ mới \nthành công
                deactivate WebControl
                MobileControl --> MobileApp: thông báo \nthêm căn hộ mới \nthành công
                deactivate MobileControl
            end
        end

    deactivate WebControl
    deactivate MobileControl
    deactivate MobileApp
    deactivate User


@enduml